apiVersion: apps/v1
kind: Deployment
metadata:
  name: geodarts-redis-deployment
spec:
  selector:
    matchLabels:
      app: geodarts-redis
  replicas: 3
  template:
    metadata:
      labels:
        app: geodarts-redis
    spec:
      containers:
        - name: game
          image: "timothygeiger/geodarts-redis:1.13"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: geodarts-redis-service
  labels:
    app: geodarts-redis
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
  selector:
    app: geodarts-redis
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: geodarts-redis-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: geodarts-redis
          servicePort: 8080
        path: /
